version: '3.9'
services:

  task-manager:
    container_name: task-manager
    build: .
    depends_on:
      - mariadb
    ports:
      - ${APP_PORT}:8080
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      WAIT_HOSTS: ${DB_HOST}:${DB_PORT}

  mariadb:
    container_name: mariadb
    image: mariadb:10.6
    restart: always
    ports:
      - ${DB_PORT}:3306
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_HOST: '%'
